### ISSUE TITLE
Features: Input queue, auto-search, extra metadata

### ISSUE THREAD

**Issue by Decimation** [Decimation/SmartImage#40]
Requested by @SakiSakiSakiSakiSaki

**Comment by SakiSakiSakiSakiSaki** [comment]
So under the assumption that `Auto-Search` is functioning correctly, and you're able to select multiple images through `[ Browse ]`.

---
- When multiple images are dragged to the program, or selected through the context menu, a queue is created.
   - If a queue already exists, these images should be added to the end of the existing queue.
   - Selecting images through `[ Browse ]` should also append them to the end of any existing queue.

- The default state of the program could have a `[ Next ]` button, perhaps below `[ Run ]`.
   - This `Next` button when clicked would automatically search the next image in the queue.
   - If there is no "next image", or if it happens to be the last of a queue (could even be a queue of 1), it does nothing.

- When you click the `[ Delete ]` button, the same behavior should occur. Switch to the next image in the queue, or do nothing if that was the last image.

That's the limit of my personal needs.

---
If you wanted to further integrate your existing setup with this queue system, here's some **super** optional ideas:
- The `[ Restart ]` button could erase the entire queue, leaving you at square one.
- I can't think of what `[ Clear ]` should do when you're in the middle of a queue. I assume it would be messy to allow a "priority" system, such that any image dropped into the program after hitting `[ Clear ]` would move to the front of the queue, being the next item searched. This sounds like a pain to be honest, so I'll leave discretion up to you.
- A separate `[ Queue ]` button, when clicked, displays the queue to you by filenames [Hard] OR a counter for how many items remain in the queue [Easy].

Thanks a lot!

**Comment by Decimation** [comment]
Here is what I have currently working for the *Queue*:

### Enqueuing items
- Check the *Queue* checkbox to enable it
- Click `[Browse]` and select the input images
- - The selected files are enqueued

### Usage
- The front of the queue is shown in the input field
- Click `[Run]` to run the search
- Click `[Next]` to dequeue the next item in the queue

### Examples

Using the file picker:

https://github.com/Decimation/SmartImage/assets/4624891/e25c195d-c04b-4155-99fd-f7df1b7b5204

Using the dialog:

https://github.com/Decimation/SmartImage/assets/4624891/bd54d730-151a-49d5-a96f-b18adc895bae

### Progress

This is what I've gotten working in the past 4 hours or so since I started working on it. I have yet to iron things out and make some adjustments per your request.

**Comment by SakiSakiSakiSakiSaki** [comment]
It's insane that you managed to cook this up in 4 hours. 

---

How do you plan on handling a queue that has 20+ items, and displaying those in that `[ Queue ]` menu? At a certain point the entire list would be too long to fit in the box. 

Since this was a optional request, I really don't want you slaving over it. 

The easy solution would be to display the first X items, and just add an ellipses at the bottom if there's more than X remaining in the queue. 

The hard solution would be to enable some sort of scroll, which would allow you to Remove items from the queue that exist after the first X items. 

Completely up to you!

---

Scalability in general is something I'm curious about, I wonder how big does the queue have to be before your PC/SmartImage starts chugging. I suppose it wouldn't be hard to calculate for your own personal machine, but it might differ on a user-basis. 

---

Something else I also wonder is, if you'd be able to "relinquish" files that have been inserted into SmartImage, so that you can manually delete them without receiving an error that SmartImage is using the file. This is super low priority since you have graciously added a Delete button, but also something to consider with long queues.

Thank you for your work!

**Comment by Decimation** [comment]
> How do you plan on handling a queue that has 20+ items, and displaying those in that `[ Queue ]` menu? At a certain point the entire list would be too long to fit in the box.
> The hard solution would be to enable some sort of scroll, which would allow you to Remove items from the queue that exist after the first X items.

You can already scroll, up/down, left/right.

> Thank you for your work!

No problem! And thank you for the generous donations.

**Comment by Decimation** [comment]
Can you try out [v3.0.3 RC](https://github.com/Decimation/SmartImage/releases/tag/v3.0.3)?

**Comment by SakiSakiSakiSakiSaki** [comment]
The `[Next]` and `[Queue]` buttons don't seem to work when I drag multiple images into the client. They are greyed out.

**Comment by Decimation** [comment]
Did you enable the queue as seen in the [examples](https://github.com/Decimation/SmartImage/issues/40#issuecomment-1552368713)? 
(Make sure you're toggling the checkbox to the left of the `[Next]` button)

###

Here is a more complete example showing both use-cases of the queue:

https://github.com/Decimation/SmartImage/assets/4624891/265f80a9-a07f-48c0-9846-33d4bba9662d

### 1. Using the file picker `[Browse]`

Select multiple files using the dialog as you would any other program. You can `Ctrl+Click` to add to the selected files or `Shift+Click` to bulk select files.

### 2. Drag-and-drop into queue input `[Queue]`

This is still being worked on. Drag and drop files into the input field in the `[Queue]` dialog, and if the input is valid, it will be automatically added to the queue.

Single file drag-and-drop only works for now. I will see if I can find a way to implement multi-file drag-and-drop into the input field.

Also, there is a minor bug as seen in the example: if the file path has spaces (which results in the path being delimited with quotes `"`), the leading quote isn't cleared from the input field. The workaround is just deleting it. I have tried ironing this bug out -- and I'm sure I will eventually -- but this seems to be another issue with the `Terminal.Gui` shell library.

**Comment by SakiSakiSakiSakiSaki** [comment]
> Single file drag-and-drop only works for now. I will see if I can find a way to implement multi-file drag-and-drop into the input field.

This explains it. Works decently with the `[Browse]` though. I assume auto-search is still in-progress too, since I can't toggle it yet.

I love the new colors, what a great idea!

Edit: Even with having to hit `[Run]` after `[Next]`/`[Delete]`, this is as smooth and reliable as I expected it would be, thanks a lot for this. I really _really_ hope others are using this tool for their own data hoarding and backlogs of images too.

**Comment by Decimation** [comment]
> Edit: Even with having to hit `[Run]` after `[Next]`/`[Delete]`, this is as smooth and reliable as I expected it would be, thanks a lot for this. I really _really_ hope others are using this tool for their own data hoarding and backlogs of images too.

Thank you! I appreciate it, and thank you for your donations. Feel free to suggest any features or improvements for **SmartImage** you would find like to see.

I am also working on image scanning within result data (the payload returned by the server URL in the results), and downloading image results (#41).

Auto-search is WIP but it's a bit tedious. Just to verify, you envision auto-search to start the search immediately after input verification and uploading, right (as it does when opening via the context menu)?

In the future, I may further upgrade the queue to run searches concurrently. The only problem is performance and overhead, both client-side and server-side. However this is just an idea in the backlog.

**Comment by SakiSakiSakiSakiSaki** [comment]
> I am also working on image scanning within result data (the payload returned by the server URL in the results), and downloading image results (https://github.com/Decimation/SmartImage/issues/41).

That's really ambitious, I hope you can pull that off. Downloading would allow others to retrieve a more "native" copy of the image they used to search.

> Auto-search is WIP but it's a bit tedious. Just to verify, you envision auto-search to start the search immediately after input verification and uploading, right (as it does when opening via the context menu)?

Oh wow, I didn't expect it pose trouble. But yes you're correct, just like how it works with the context menu. After uploading is complete.

> In the future, I may further upgrade the queue to run searches concurrently. The only problem is performance and overhead, both client-side and server-side. However this is just an idea in the backlog.

Yea this is something that would have to be done delicately, since some of the search engines you've provided have hard limits on the amount of searches that can be done in a given span of time. You'd probably have to program a back-off period between searches or something, either globally, or on a search engine basis. Honestly sounds like a lot of mapping, since you'd really only have to account for the largest back-off period of all the selected engines.

What's funny about this is that while SauceNao only allows 3 searches in a 30 second period, SmartImage still returns the resulting links, just with a broken raw SauceNao link.

**Comment by SakiSakiSakiSakiSaki** [comment]
Found a bug for this release:
Ascii2D and SauceNao are giving me errors when I hit `[Run]`, queue or not. Sometimes the SmartImage UI does present the resulting urls, but the raw websites would produce that error:

Ascii2D:
![image](https://github.com/Decimation/SmartImage/assets/41088844/79504a5f-8a0e-4a89-b4f1-3f59d655a58e)

SauceNao:
![image](https://github.com/Decimation/SmartImage/assets/41088844/5424d39b-197f-4269-9d18-521b188948a0)

The other engines don't result in anything either.

**Comment by Decimation** [comment]
> Found a bug for this release: Ascii2D and SauceNao are giving me errors when I hit `[Run]`, queue or not. Sometimes the SmartImage UI does present the resulting urls, but the raw websites would produce that error:
> 
> Ascii2D: ![image](https://user-images.githubusercontent.com/41088844/241593504-79504a5f-8a0e-4a89-b4f1-3f59d655a58e.png)
> 
> SauceNao: ![image](https://user-images.githubusercontent.com/41088844/241593516-5424d39b-197f-4269-9d18-521b188948a0.png)
> 
> The other engines don't result in anything either.

- Are these bugs consistent (regardless of the input you use) or specific to certain inputs? Can you share the inputs which caused these errors, and your configuration?

- Does the latest stable release (`v3.0.2`) have this issue?

- **Note:** I also updated the executable for that release a few times, so make sure you're using the most recent `v3.0.3 RC`.

**Comment by SakiSakiSakiSakiSaki** [comment]
>Are these bugs consistent (regardless of the input you use) or specific to certain inputs? Can you share the inputs which caused these errors, and your configuration?

https://github.com/Decimation/SmartImage/assets/41088844/99560c34-94d5-450e-b10b-e82728bdbb29
![image](https://github.com/Decimation/SmartImage/assets/41088844/5de1b4d3-acdb-48cc-976e-0707c98fb673)

>Does the latest stable release (v3.0.2) have this issue?

Yes

>Note: I also updated the executable for that release a few times, so make sure you're using the most recent v3.0.3 RC.

Just tried it, same issue.
v3.0.3 worked earlier a few hours ago. I changed my IP address via VPN a few times as well.

**Comment by Decimation** [comment]
Does this issue happen regardless of the image you use? Can you share one of the images you searched?

**Comment by Decimation** [comment]
Looking at the image you searched, https://files.catbox.moe/t87qii.jpg, it seems CatBox had an error uploading it, or the original image you used (which was uploaded to the aforementioned URL), is corrupt or of a unique format.

![firefox_2023-05-28_(18h38m37s)_L22a2nex1Y](https://github.com/Decimation/SmartImage/assets/4624891/87392e80-3ac7-4630-8611-53f5c4654759)

CatBox doesn't return any data from that URL which is why _some_ of the engines don't return any results. The reason the `[Raw]` results give an error is because the API retrieves its data from the upload URL (which doesn't return any data as explained below), whereas the normal results are returned by the API with the image file itself used as the request payload (it's not using the upload URL).

```
curl 'https://files.catbox.moe/t87qii.jpg' > test.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

The fact this issue is only occurring now, and given CatBox is returning an error, makes me inclined to believe either (1) there's something with the images you're searching; or (2) CatBox can't properly handle the image. Can you share the image(s) you search which results in this error? Also, does this issue occur _only_ when searching some of these images, or is it _any_ image?

If there's something unique to the image format, I can work something out probably.

**Comment by SakiSakiSakiSakiSaki** [comment]
It's any image.
![Screenshot_353251](https://github.com/Decimation/SmartImage/assets/41088844/1db0066e-f6c3-46c3-aad1-da64740534f1)
![DjOlhMIUcAAHjm1](https://github.com/Decimation/SmartImage/assets/41088844/b93c2172-4036-46e5-afe1-c518f77d2e73)

**Comment by Decimation** [comment]
> It's any image. ![Screenshot_353251](https://user-images.githubusercontent.com/41088844/241597805-1db0066e-f6c3-46c3-aad1-da64740534f1.png) ![DjOlhMIUcAAHjm1](https://user-images.githubusercontent.com/41088844/241597871-b93c2172-4036-46e5-afe1-c518f77d2e73.jpg)

I just tested uploading those images to *CatBox* and *Litterbox*, and it seems the issue is caused by *CatBox* itself; *Litterbox* uploads them just fine and returns the data properly. This isn't a bug with *SmartImage* itself, but I can add error handling to use *Litterbox* as a backup in case *CatBox* is having problems.

**Comment by SakiSakiSakiSakiSaki** [comment]
Great! Glad we found this lol.

**Comment by Decimation** [comment]
After further research, it seems *CatBox* doesn't like images with `EXIF`/`XMP` metadata. If you clear the metadata, *CatBox* will work properly. You can clear metadata by using the following option in the `Properties > Details` dialog in Explorer:

![explorer_2023-06-04_(13h00m42s)_LiMJlhxs7q](https://github.com/Decimation/SmartImage/assets/4624891/4198a841-3a7d-4597-bc7a-09d01424855e)

I am looking into ways to automate this in **SmartImage**.

**Comment by SakiSakiSakiSakiSaki** [comment]
> After further research, it seems _CatBox_ doesn't like images with `EXIF`/`XMP` metadata. If you clear the metadata, _CatBox_ will work properly. You can clear metadata by using the following option in the `Properties > Details` dialog in Explorer:
> 
> ![explorer_2023-06-04_(13h00m42s)_LiMJlhxs7q](https://user-images.githubusercontent.com/4624891/243198553-4198a841-3a7d-4597-bc7a-09d01424855e.png)
> 
> I am looking into ways to automate this in **SmartImage**.

Oh that's weird, cause I was dragging images with metadata for a long while til it randomly stopped working. Wonder if they changed anything.

**Comment by Decimation** [comment]
@SakiSakiSakiSakiSaki Can you try out the latest [`v3.0.3 RC`](https://github.com/Decimation/SmartImage/releases/tag/v3.0.3)?

**Comment by SakiSakiSakiSakiSaki** [comment]
Just tried it out, the `auto-search` is intensely useful. You can just power through a bunch of images, one after another.

I noticed a few things:
- I'm aware that multi-image drag and drop is not supported yet. Doing so right now, crashes the program:
https://github.com/Decimation/SmartImage/assets/41088844/79a4ef62-e4ac-4072-9027-6992d63eb92e

- After a successful batch search through `[Browse]`, trying another batch search through drag and drop will only search the first image of the batch, but oddly doesn't let you `[Delete]` the image.
https://github.com/Decimation/SmartImage/assets/41088844/fb402871-274e-4053-8a43-962828a73fbd

As an aside:
- For SauceNao, would it be possible to also grab these links to Boorus as well?
![image](https://github.com/Decimation/SmartImage/assets/41088844/00864e75-2b52-4a95-8812-3e4d19d92ed9)
Sometimes the results populate in SmartImage, sometimes they don't.


Thanks a lot for this!

**Comment by Decimation** [comment]
## Point 1 & 2

Multi-file drag-and-drop **does not** work for the input field (it never has). I can try to make a workaround for this, but it's another limitation of `Terminal.Gui`. To use the queue, use the `[Browse]` button to select multiple files (after enabling it as described [earlier](https://github.com/Decimation/SmartImage/issues/40#issuecomment-1565220521) in the thread).

## Point 2

This is because the input field only accepts a single file. When you try to drag-and-drop multiple files into the input field, it is converted into a string with the format `file1 file2 filen`. There is slight overhead with this. Auto-search invokes once a valid input is detected in the input field, and it detected the first file, then ran.

## SauceNao

I believe this is already implemented but I'm not entirely sure. If not, I'll add it.

Have you checked the other result columns (there are arrows in the table borders indicating hidden columns aren't shown) to see if the SauceNao result contains the other links? Use the directional arrow keys to navigate through the table.

**Comment by SakiSakiSakiSakiSaki** [comment]
> Point 1 & 2
Point 2

Yea that's fine, I figured it was a library limitation.
When you use `[Browse]` yourself, is the resulting file explorer window ever lower resolution than your normal file explorer windows? I use a 4K display, and the resolution on the created file explorer looks a lot less:
From SmartImage:
![image](https://github.com/Decimation/SmartImage/assets/41088844/1d06e2ea-1e97-430a-b778-50a0fd1abf3d)
Native:
![image](https://github.com/Decimation/SmartImage/assets/41088844/7475f484-0717-4241-8411-0c15440c0a7f)

---
> SauceNao

I'll do some more research and see if I can find examples. I've actually never noticed hidden columns before, so that's good to know.

Thanks!

**Comment by Decimation** [comment]
I'm pretty sure the reason the dialog is lower resolution is due to [Windows resolution scaling](https://support.microsoft.com/en-us/topic/windows-scaling-issues-for-high-dpi-devices-508483cd-7c59-0d08-12b0-960b99aa347d). This affects most programs running on any high-DPI (≥2K resolution, Surface displays, etc.) device — it's more an issue with Windows handling high DPI. If it's really bothersome, I can see if I can make the process "DPI-aware" but testing it would be tricky.

**Comment by SakiSakiSakiSakiSaki** [comment]
I wouldn't worry about it, seems like it's something that should go further down the totem pole, when it's the last pressing thing left.

Everything else works pretty great though, this program is like a well-oiled machine. My only gripe is SauceNao's aggressive limit-rating, which your program partially circumvents by returning SauceNao's results either way, just without the raw link since it'd be under cooldown.

I imagine there's billions of API specific engine issues when you look at all the engines you allow users to use, beyond my personal use-cases lol.

**Comment by Decimation** [comment]
I'm pleased to hear it's working efficiently! 

Does the download feature work? 

- Select a link in the results table (column 3) then use the keystroke `Ctrl+D`. *Make sure the cursor is in the link cell `_`*
 - If the link is a direct link to an image (the payload is a binary image file), a ✓ will appear in the column to the left (column 2). Otherwise, a × will appear.
- You can then double-click the corresponding result name (column 1) to open the folder in which the file downloaded (your user `Pictures` folder by default). The file will be highlighted as well.

**Comment by SakiSakiSakiSakiSaki** [comment]
I've been pressing `Ctrl+D` on my rows, using the following image:
![FDHqpOYaIAAkTg_](https://github.com/Decimation/SmartImage/assets/41088844/fdab60f6-c75e-44ef-939f-2ad8147fecdc)

I sometimes don't see the underscore, or when I do, and I do the keystroke, the ✓ or × only appears when I click on another row.

I got a check from a single url:
![image](https://github.com/Decimation/SmartImage/assets/41088844/0be05fbc-f65c-4524-80ee-f9c73831e930)

Clicking column 1 results in nothing, and my `Pictures` folder is empty as well.

**Comment by Decimation** [comment]
The `×` means you can't download the URL because it's not a direct URL to an image, therefore it wasn't downloaded.

**Example**

URL returns an image file (direct URL): `https://www.catbox.moe/file/image.png` → ✓

URL returns an HTML page: `https://www.iqdb.org` → ×

A heuristic is whether or not the URL has a filename with an image extension. The reason every result URL isn't checked automatically is to limit API and server calls in addition to performance costs.

*Yandex* and *RepostSleuth* tend to have direct URLs but others sometimes have them as well.

>I sometimes don't see the underscore, or when I do, and I do the keystroke, the ✓ or × only appears when I click on another row.

The download/scan process is asynchronous and the duration depends on the server response time and the payload returned.



I am also working on image scanning within result data for image URLs (#41). For instance, a *danbooru* result URL may have a download link to the full-size original image within the page HTML.

**Comment by SakiSakiSakiSakiSaki** [comment]
I think the program had a memory leak lol
![image](https://github.com/Decimation/SmartImage/assets/41088844/f5167dbc-0532-4284-b43c-28c852b03f44)

It kept taking forever to search for an image, and cancelling and move the next image didn't change anything.

**Comment by Decimation** [comment]
> I think the program had a memory leak lol
> 
> It kept taking forever to search for an image, and cancelling and move the next image didn't change anything.

Yeah I've been ironing out memory leak issues for a while. Can you describe how you used the program (what actions, etc.) until you noticed the memory leak?

**Comment by SakiSakiSakiSakiSaki** [comment]
I just dumped about 40 images or so through Browse. Skipping or deleting, til one image was hanging up for a long while.

**Comment by Decimation** [comment]
> I just dumped about 40 images or so through Browse. Skipping or deleting, til one image was hanging up for a long while.

Can you try the updated `v3.0.3 RC` build? I think I may have resolved the memory leaks (partially). I just queued 72 images totaling 187 MB and the process ran fine. Can you describe or share the image which caused the program to hang?

**Comment by SakiSakiSakiSakiSaki** [comment]
75 images works for me as, with that new build.

Some things I just noticed:
- The Google Images engine search just returns the Google Image homepage:
![image](https://github.com/Decimation/SmartImage/assets/41088844/6915dae3-5f21-403d-b686-950d9170fce9)
![image](https://github.com/Decimation/SmartImage/assets/41088844/dbf6c021-20c9-454c-98f0-e64c1199f87c)

- Here is an image, when searched on SauceNao, does not return the Danbooru/Gelbooru link.
![0f1988731d7e78923e678465493899c0](https://github.com/Decimation/SmartImage/assets/41088844/1c68671b-8cba-4f81-9ee8-6fceaa996ff3)
![image](https://github.com/Decimation/SmartImage/assets/41088844/3bb0f6ef-b917-40bf-8676-9e661f5d5593)

- I feel like `[Run]` should be disabled if no engines are selected, intuitively.

**Comment by Decimation** [comment]
Try out the latest `v3.0.3 RC`.

>The Google Images engine search just returns the Google Image homepage

*Google Images* replaced their image search feature with *Google Lens*. I updated the *Google Images* search URL to use *Google Lens* so it will work properly now.

>Here is an image, when searched on SauceNao, does not return the Danbooru/Gelbooru link

Extraneous URLs (extra URLs) are stored in the `Metadata` field column. I added a feature to view extra metadata in the latest release: press `Ctrl+M` and a dialog will show:

![SmartImage_2023-06-10_(13h34m13s)_FuJHiRWf7J](https://github.com/Decimation/SmartImage/assets/4624891/cbdd5836-c21d-429a-897b-a67cecfa5408)

You can double click the URLs to open them in your browser.

Let me know if you have a more intuitive or preferential method of viewing extra metadata or URLs.

>I feel like [Run] should be disabled if no engines are selected, intuitively.

Whenever no engines are selected, **SmartImage** reverts back to the default engine selection (`All`).

**Comment by Decimation** [comment]
I also added hotkeys for efficiency:

|  Key | Function |
| --- | --- |
| `Ctrl+R` | Restart |
| `Ctrl+B` | Browse |
| `Ctrl+C` | Cancel |
| `Ctrl+N` | Next |

**Comment by SakiSakiSakiSakiSaki** [comment]
Hi friend, apologies for the delayed response. I have just tried out the latest build, here are my responses to your above response:

> Extraneous URLs (extra URLs) are stored in the `Metadata` field column. I added a feature to view extra metadata in the latest release: press `Ctrl+M` and a dialog will show:
> You can double click the URLs to open them in your browser.
> 
> Let me know if you have a more intuitive or preferential method of viewing extra metadata or URLs.

This is great, although I have a question. What constitutes as metadata? I assumed both Danbooru and Gelbooru would be metadata, not just Gelbooru. 

**Complex Solution**: I think the most intuitive thing for those tiny buttons would be to "indent" them or group them under the result box they appear in. In reference to the image you and I used, `SauceNao #2` and `SauceNao #3` would be grouped under `SauceNao #1`, as `SauceNao #1.1` and `SauceNao #1.2` respectively.

![image](https://github.com/Decimation/SmartImage/assets/41088844/ced1275c-e21e-44c7-97e6-0bbc58c9e359)


**Simple Solution:** Another idea would be to just embed the metadata items as their own row/result. So the `gelbooru` and `twitter` links would be their own rows as `SauceNao #4` and `SauceNao #5` respectively. 

---
---

> Whenever no engines are selected, **SmartImage** reverts back to the default engine selection (`All`).

That's _perfectly_ fine with me, but when I deselect all engines and try to search, the `Uploading` bar will hang up for a few seconds, and return nothing instead of everything:

![image](https://github.com/Decimation/SmartImage/assets/41088844/d57ee189-91f7-4aa3-aa73-26ddf165b837)
![image](https://github.com/Decimation/SmartImage/assets/41088844/54f3da54-cc0a-461f-bf1d-50c086436741)

---
---

Side Notes:
- I think it would help to make the default window size wide enough to address the following two issues:
  - You can't see the loading bar and loading status in the current default size without having to extend the window.
   ![image](https://github.com/Decimation/SmartImage/assets/41088844/05dd6632-82d3-4680-b23a-4d6c6c0bb3a3)
   - The menu text overflows into whitespace.
   ![image](https://github.com/Decimation/SmartImage/assets/41088844/d75cc4f7-71f7-4977-b831-3a98424967db)

---
---

Hope this helps, thanks!

**Comment by Decimation** [comment]
Try out [v3.0.3-RC2](https://github.com/Decimation/SmartImage/releases/tag/v3.0.3-rc2). I implemented the extraneous URL handling like you described.

**Comment by SakiSakiSakiSakiSaki** [comment]
Yea this is great. One suggestion I have is probably omitting the "lookup_type" urls:
![image](https://github.com/Decimation/SmartImage/assets/41088844/1be79a95-0a76-4597-9cb8-f165aed8ddfe)
Those are links to these buttons:
![image](https://github.com/Decimation/SmartImage/assets/41088844/a3d0e486-50a7-4db4-a72a-1beb3eb6745a)
Which are inaccessible to most people since it requires a premium SauceNao account.
![image](https://github.com/Decimation/SmartImage/assets/41088844/8636c589-ba41-425b-8bab-777ecf065b32)

---

I noticed a new `[Filter]` button. Not sure what it does yet though haha.

---

Are you able to receive Ascii2d results for that above image Donguri Suzume image? I get the following:
![image](https://github.com/Decimation/SmartImage/assets/41088844/b2661cb0-580f-40f9-923c-deb0106c13c1)

**Comment by Decimation** [comment]
Can you try the updated [v3.0.3-RC2](https://github.com/Decimation/SmartImage/releases/tag/v3.0.3-rc2)? 

- *SauceNao* `lookup_type` URLs are filtered.
- *Ascii2D* timeout was increased to 10 seconds. The reason *Ascii2D* wasn't returning results for that image was because it was timing out.

`[Filter]` filters out low-quality results from the table. Each click increases the filter level (`3` being the highest). Filter level `3` will only show direct image links.

**Comment by SakiSakiSakiSakiSaki** [comment]
Nice! I'd also suggest removing the artist links from SauceNao, given how often they'll repeat:
![Screenshot_1](https://github.com/Decimation/SmartImage/assets/41088844/7b9b7644-4551-431f-8617-68de61642cda)

![Screenshot_2](https://github.com/Decimation/SmartImage/assets/41088844/b9a88e3c-390a-419a-bc0b-020f90e353ac)

**Comment by Decimation** [comment]
> I'd also suggest removing the artist links from SauceNao, given how often they'll repeat:

I just released [v3.0.3](https://github.com/Decimation/SmartImage/releases/tag/v3.0.3) with this change. Can you try it out? Here is how the results should look using the same image in your example:

![VsDebugConsole_2023-07-04_(08h56m38s)_YxIaS2qRB5](https://github.com/Decimation/SmartImage/assets/4624891/b8614767-9ba6-42d6-8450-cc21b60554b4)

**Comment by SakiSakiSakiSakiSaki** [comment]
I just tried out [v3.0.3 RC 2](https://github.com/Decimation/SmartImage/releases/tag/v3.0.3-rc2) and noticed a few things with the following image:
![43043883_p0](https://github.com/Decimation/SmartImage/assets/41088844/93353cbf-fcf1-4276-b504-851718c1b61f)

- Users still shows up for that above image, intended?
- The artist field wasn't grabbed for those various entries.
- Program has trouble parsing non-latin characters I think. Not sure how much trouble it would be to support that unicode encoding.

![image](https://github.com/Decimation/SmartImage/assets/41088844/5e00612d-675d-4d82-be55-9e6cef6a8cd7)

---

As a side note, I've spent hours using your program to organize my images. It's really great. Was wondering it would be possible to add a queue counter of sorts. Like how many images are remaining in the queue or something. Anywhere would be fine, so as long as it updated.

**Comment by Decimation** [comment]
Can you try the final [v3.0.3](https://github.com/Decimation/SmartImage/releases/tag/v3.0.3) release, not RC 2? RC builds were release candidates for testing.

As for the non-Latin characters not rendering, that's caused by the console encoding mode and whether the console font supports such characters. You can try changing the default console font by configuring Command Prompt defaults.

I can definitely add a queue counter in. Feel free to request any other features you'd like as well.

And thank you for the support! I'm glad to hear the software is working so well.

**Comment by Decimation** [comment]
@SakiSakiSakiSakiSaki Actually, could you try out [v3.0.4](https://github.com/Decimation/SmartImage/releases/tag/v3.0.4)?

### Queue

I added the queue counter as you requested.

### SauceNao

#### Results

As for the `user` results from *SauceNao*, the Twitter username is now parsed:

![2023-07-08_(13h23m13s)_6f3Sgnx5Ew](https://github.com/Decimation/SmartImage/assets/4624891/e0f171dc-c26d-41b0-9ad4-f59dbc92fd07)

I don't want to remove the user link entirely because other users may find it useful. Additionally it helps isolate an artist's official Twitter from other accounts which may just be reposting their artwork. I hope that's fine with you.

#### API

You can now use the official _SauceNao_ API by entering an API key in the config dialog. This will be more reliable and faster.

### Console encoding

SmartImage sets the console encoding to UTF-8 on startup so non-Latin characters should render properly, but it doesn't seem to work. Running SmartImage with Windows Terminal works, but the console buffer/window is janky. I've tried resolving this before for other projects but to no avail. I think the console font has something to do with it as well.

**Comment by SakiSakiSakiSakiSaki** [comment]
> @SakiSakiSakiSakiSaki Actually, could you try out [v3.0.4](https://github.com/Decimation/SmartImage/releases/tag/v3.0.4)?

Seems like `[ Config ]` is inaccessible until SmartImage.dll.config generates. The program has been closed and reopened upon first instance.

Once I can get `[ Config ]` open, I can't change anything. I have additional files generate. 
![image](https://github.com/Decimation/SmartImage/assets/41088844/f8912c38-bb9e-4e09-b918-ecbf2f355c95)

> ### SauceNao
> #### Results
> As for the `user` results from _SauceNao_, the Twitter username is now parsed:

> I don't want to remove the user link entirely because other users may find it useful. Additionally it helps isolate an artist's official Twitter from other accounts which may just be reposting their artwork. I hope that's fine with you.

Yea that's perfectly fine with me.

> #### API
> You can now use the official _SauceNao_ API by entering an API key in the config dialog. This will be more reliable and faster.

This would be great if the API was generous lol. I'll just stick to guest and using VPN lol.

**Comment by Decimation** [comment]
> Seems like `[ Config ]` is inaccessible until SmartImage.dll.config generates. The program has been closed and reopened upon first instance.
> 
> Once I can get `[ Config ]` open, I can't change anything. I have additional files generate.

Thanks for the report. I updated [v3.0.4](https://github.com/Decimation/SmartImage/releases/tag/v3.0.4) with a fix. Can you try it out?

**Comment by SakiSakiSakiSakiSaki** [comment]
> Thanks for the report. I updated [v3.0.4](https://github.com/Decimation/SmartImage/releases/tag/v3.0.4) with a fix. Can you try it out?

 Works perfectly. Thanks!

**Comment by SakiSakiSakiSakiSaki** [comment]
> Thanks for the report. I updated [v3.0.4](https://github.com/Decimation/SmartImage/releases/tag/v3.0.4) with a fix. Can you try it out?

I seem to be getting this error after a while, after I configure all my stuff etc. Fixes itself by deleting my config file:

![image](https://github.com/Decimation/SmartImage/assets/41088844/5168ec8a-5622-4a9f-9370-a8f5508e47bd)
[SmartImage.zip](https://github.com/Decimation/SmartImage/files/11996150/SmartImage.zip)

**Comment by Decimation** [comment]
> I seem to be getting this error after a while, after I configure all my stuff etc. Fixes itself by deleting my config file:

Thanks for reporting this. It was a simple mistake on my part. I just pushed a fix [v3.0,.4](https://github.com/Decimation/SmartImage/releases/tag/v3.0.4).

I also implemented image scanning. Use the keystroke `Ctrl+S` on a result and it will scan for image links within the page. I will update the wiki with more info later.


![SmartImage_2023-07-09_(18h46m08s)_oFdiVWP5w4](https://github.com/Decimation/SmartImage/assets/4624891/cc386c47-9be3-4f1d-9db1-9b81aefe561b)

**Comment by Decimation** [comment]
I'm marking this task as complete and closing the issue. I think everything has been implemented fully.

In regard to the bug, I assume the latest v3.0.4 fix worked for you? If not, feel free to open a (new) issue.

**As always, post any suggestions in this [discussion thread](https://github.com/Decimation/SmartImage/discussions/35)**

**Comment by SakiSakiSakiSakiSaki** [comment]
> I'm marking this task as complete and closing the issue. I think everything has been implemented fully.
> 
> In regard to the bug, I assume the latest v3.0.4 fix worked for you? If not, feel free to open a (new) issue.
> 
> **As always, post any suggestions in this [discussion thread](https://github.com/Decimation/SmartImage/discussions/35)**

Yep, everything's been smooth sailing. Thanks!
